import { applyDamage } from '../engine/damagePipeline.js';

// Lunar Eclipse: flat 3-attack duration, no coin flip. Untargetable covers
// her next 3 attacks after casting, then ends automatically.
function maybeEndEclipse(character, log) {
  if (!character.untargetable) return;
  character.special.eclipseAttacksSinceCast += 1;
  if (character.special.eclipseAttacksSinceCast < 3) return;
  character.untargetable = false;
  log.push({ type: 'eclipse-end', characterId: character.id });
}

const MOONLIT_THEFT_HEARTS_THRESHOLD = 3;

export const actions = {
  lunarStrike: {
    label: 'Lunar Strike',
    needsTarget: true,
    isLegal: () => true,
    execute(character, targetId, game, log) {
      character.special.hasActedOnce = true;
      character.special.lastTargetId = targetId;
      const result = applyDamage(game, log, {
        sourceCharacterId: character.id,
        targetCharacterId: targetId,
        amount: 1,
        ignoresShield: true,
      });
      log.push({ type: 'attack', characterId: character.id, actionId: 'lunarStrike', targetId, ...result });
      maybeEndEclipse(character, log);
      return result;
    },
  },
  moonstep: {
    label: 'Moonstep',
    needsTarget: true,
    isLegal: (character) => character.special.hasActedOnce,
    execute(character, targetId, game, log) {
      // No bonus on her first-ever real attack (e.g. opened with Lunar
      // Eclipse instead of Lunar Strike) - lastTargetId is null then, and
      // that must NOT count as "a different target" for the -2 bonus.
      const isNewTarget = character.special.lastTargetId !== null
        && character.special.lastTargetId !== targetId;
      const amount = isNewTarget ? 2 : 1;
      character.special.lastTargetId = targetId;
      const result = applyDamage(game, log, {
        sourceCharacterId: character.id,
        targetCharacterId: targetId,
        amount,
        ignoresShield: true,
      });
      log.push({ type: 'attack', characterId: character.id, actionId: 'moonstep', targetId, isNewTarget, ...result });
      maybeEndEclipse(character, log);
      return result;
    },
  },
  lunarEclipse: {
    label: 'Lunar Eclipse',
    needsTarget: false,
    special: true,
    isLegal: (character) => !character.usedSpecial,
    execute(character, targetId, game, log) {
      character.usedSpecial = true;
      character.untargetable = true;
      character.special.hasActedOnce = true;
      character.special.eclipseAttacksSinceCast = 0;
      log.push({ type: 'special', characterId: character.id, actionId: 'lunarEclipse' });
      return {};
    },
  },
  // Moonlit Theft (taxonomy #35 Siphon, design-locked 2026-09-11): hearts<=3
  // one-time special. Drains every OTHER currently-living character's
  // shield down to 0, sums the total, and adds it to Velorya's own current
  // shield - a genuine one-directional transfer, not a Lifebond-style
  // averaged split. Deliberately does NOT route through applyShield - this
  // isn't a normal shield GRANT (it must still work even while she herself
  // is silenced, since the shield is stolen, not generated by a source
  // isSilenced would block; matches how Lifebond also bypasses
  // applyDamage/applyHeal for the same "this isn't a normal instance of
  // that mechanic" reasoning). Uses `+=` rather than a flat assignment even
  // though nothing in her kit grants her shield today, so this stays
  // correct without revisiting if a future ability ever does.
  moonlitTheft: {
    label: 'Moonlit Theft',
    needsTarget: false,
    special: true,
    isLegal: (character) => character.hearts <= MOONLIT_THEFT_HEARTS_THRESHOLD && !character.special.usedMoonlitTheft,
    execute(character, targetId, game, log) {
      character.special.usedMoonlitTheft = true;
      const others = Object.values(game.characters).filter((c) => c.id !== character.id && !c.isKO);
      const changes = [];
      let stolenTotal = 0;
      for (const c of others) {
        if (c.shield > 0) {
          changes.push({ characterId: c.id, before: c.shield, after: 0 });
          stolenTotal += c.shield;
          c.shield = 0;
        }
      }
      const shieldBefore = character.shield;
      character.shield += stolenTotal;
      log.push({
        type: 'special', characterId: character.id, actionId: 'moonlitTheft',
        changes, stolenTotal, shieldBefore, shieldAfter: character.shield,
      });
      return {};
    },
  },
};
